name: Update Translation Count
on:
  push:
    paths:
      - 'assets/translations/**'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get language count
        id: count
        run: |
          TOTAL=$(ls assets/translations | wc -l)
          COUNT=$((TOTAL - 3))
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Create Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: YOUR_GIST_ID_HERE
          filename: languages.json
          label: Languages
          message: ${{ steps.count.outputs.count }}
          color: orange
